version: '3.2'

services:
  letsencrypt:
    build:
      context: .
    image: andyneff/letsencrypt:latest
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
